### ISSUE TITLE
Min-Max limits for component width/height

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1360]
**Originally by @jojule**

___
For more flexible automatic layouts min-max sizing is sometimes needed. See http://cappuccino.org/learn/tutorials/automatic-layout/ for a nice example implemented by a competitor.

We should create LimitedSizeable interface extends Sizeable that includes:
 - float getMinWidth()
 - setMinWidth(String)
 - setMinWidth(float, int unit)
 - int getMinWidthUnits()
 - setMinWidthUnits(int unit)
 - float getMinHeight()
 - setMinHeight(String)
 - setMinHeight(float, int unit)
 - int getMinHeightUnits()
 - setMinHeightUnits(int unit)
 - float getMaxWidth()
 - setMaxWidth(String)
 - setMaxWidth(float, int unit)
 - int getMaxWidthUnits()
 - setMaxWidthUnits(int unit)
 - float getMaxHeight()
 - setMaxHeight(String)
 - setMaxHeight(float, int unit)
 - int getMaxHeightUnits()
 - setMaxHeightUnits(int unit)

LimitedSizeable interface should be implemented by all classes that implement Sizeable today.

**Comment by Pereitor** [comment]
Wow, I'm surprised that almost 7 years after being opened such a basic feature request, it's still open and undone.

I'm facin a problem with a Window, where I don't want to specify explicit dimensions for it as I'd expect it to grow dynamically to fit its contents. This works well until its contents make the window outgrow the height of the screen. I would expect a vertical scrollbar to automatically appear, but instead the window is cut and you cannot reach its "outgrown" content. The scrollbar only appears if you explicitly set a height, let's say, "90%". But what if the contents of the window only take, let's say, 20% height of the screen? Why do I want my window to have that extra 70% blank space just to be able to scroll in case it outgrows? 

There should be a .setMaxHeight() method or whatever.

**Comment by jouni** [comment]
Thanks for the feedback! It is a bit strange, I admit, to not have built-in support for this yet. But we haven’t actually seen a big demand for this, so we’ve prioritized other things.

The use case you describe with the Window is probably the most often requested, and I provided a workaround for that just recently in the [Frameowork Gitter chat](https://gitter.im/vaadin/vaadin).

Use this as your window content structure:

```
.v-csslayout (flex-column) <— window root content layout
   .v-csslayout (scrollable flex-1) <— whatever content
   .v-csslayout (flex-shrink-0) <— footer
```

Add this CSS to your theme:

```css
.v-window {
  display: flex;
  flex-direction: column;
  max-height: calc(100% - 48px);
  overflow: hidden !important;

.v-window .popupContent,
.v-window .v-window-wrap,
.v-window .v-window-contents,
.v-window .v-scrollable {
  display: flex;
  flex-direction: column;
  position: initial;
}

.v-window .v-window-outerheader {
  display: flex;
  flex-shrink: 0;
}

.v-window .v-window-contents {
  flex: 1;
}

.v-window .v-window-contents  > .v-scrollable {
  overflow: hidden;
}
```

**Comment by ssindelar** [comment]
Not having minimum/maximum sizes ist quite annoying. Usually it is possible to find some workaround but it is always tricky or you need to change the layout. I encounter this problem on average maybe every 1-2 months. I wonder if it is just me that prefers dynamically sized windows and everyone else prefers a fixed size. Maybe you don't see a high demand for that feature because everyone knows some workaround but is still annoyed.

I hope you can find some time after the 8.1 release to add this. Even if it maybe just some checklist feature.

**Comment by heruan** [comment]
This is vital for responsiveness. I have a `Panel` with a certain width, which I don't want to expand when the screen is wide, but I want it to shrink on mobile devices: I've imported the Bootstrap Grid login to my theme, but I really think this should be core in Vaadin.

**Comment by FRC-Zach** [comment]
This would be a very useful feature.

**Comment by Artur-** [comment]
This is available in Vaadin 10 through `someComponent.getElement().getStyle().set("maxWidth", "100px")`. There it works out of the box as there are no custom layout implementations but instead the layouts rely on the browser flexbox implementation.

Do you think it is such a common use case that there should be `someComponent.setMaxWidth("100px")`?

**Comment by ssindelar** [comment]
It's nice that it will finally be solved with Vaadin 10. I don't it's so common that it needs a shortcut.
But I would really like to see it also in Vaadin 8 because till the release of Vaadin 10 it will be quite some time. 2019? Also I think the migration from Vaadin 8 to 10 will be a lot harder than 7 to 8. So I think most of us will still be on Vaadin 8 in 2020. So I would be nice to see this feature in Vaadin8 (maybe with full access to the element style like Vaadin 10 :) ), if it isn't to much work.

**Comment by galcyurio** [comment]
For those who are looking for solutions in the future.
There are 2 solution through CSS which are a bit annoying.

1. Sets custom theme.
2. declare min-max class like following.
````css
@mixin mytheme {
  @include valo;

  .max-size-100 {
    max-width: 100px;
    max-height: 100px;
  }
}
````
3. Use `Component.addStyleNames()` method like following.
````java
new Button("TEST").addStyleName("max-size-100");
````


Or, you can just dynamically injecting CSS instead of custom theme.
See [here](https://vaadin.com/docs/v8/framework/articles/DynamicallyInjectingCSS.html).

----------------------------
Is there a plan to add this min-max feature to vaadin8?
