### ISSUE TITLE
Grid with padding

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#8355]
Vaadin version:  7.7.6

I have a simple grid with hideable columns and wanted to add it a top padding. The table content got pushed down as expected, but the sidebar menu button stayed on top. The sidebar menu button should be pushed down just like everything else in that grid.

This is how it looks like:
![padding-top](https://cloud.githubusercontent.com/assets/618879/22373447/2fd94b6e-e4a2-11e6-901c-dd8653004383.png)

### Example

Servlet:
````java
@Theme("mytheme")
public class Demo extends UI {

	@Override
	protected void init(VaadinRequest vaadinRequest) {
		Grid grid = new Grid("Demo Grid");

		Column c1 = grid.addColumn("Column 1");
		Column c2 = grid.addColumn("Column 2");
		Column c3 = grid.addColumn("Column 3");

		setHidable(c1, c2, c3);

		setContent(grid);
	}

	private void setHidable(Column... columns) {
		for (Column column : columns) {
			column.setHidable(true);
		}
	}

	@WebServlet(urlPatterns = "/*", name = "MbjServlet", asyncSupported = true)
	@VaadinServletConfiguration(ui = Demo.class, productionMode = false)
	public static class MbjServlet extends VaadinServlet {
	}
}
````

mytheme.scss
````scss
@import "../valo/valo.scss";

@mixin mytheme {
  @include valo;

  // Insert your own theme rules here\}
 .v-grid {
   padding-top: 77px;
 }
}
````
