### ISSUE TITLE
New Tree component theme

### ISSUE THREAD

**Issue by jouni** [vaadin/framework#9310]
## Selection styles

The selection styles should encapsulate the whole item instead of only the caption.

### Incorrect (current):
![screen shot 2017-05-12 at 13 16 56](https://cloud.githubusercontent.com/assets/66382/25994121/4cef8e32-3715-11e7-9739-b680fcd52246.png)

### Correct:
![screen shot 2017-05-12 at 13 16 40](https://cloud.githubusercontent.com/assets/66382/25994131/53efbf90-3715-11e7-89cb-4c07602c1e4d.png)

## Focus styles

The focus styles should also wrap the whole row, not just the caption.

#### Non-selected row focused
![screen shot 2017-05-12 at 13 36 16](https://cloud.githubusercontent.com/assets/66382/25994797/032ba40e-3718-11e7-8e2e-306c2e530923.png)

#### Selected row focused
![screen shot 2017-05-12 at 13 36 04](https://cloud.githubusercontent.com/assets/66382/25994832/35ef8374-3718-11e7-9125-34528d041a79.png)

#### Non-selected row focused
![screen shot 2017-05-12 at 13 34 16](https://cloud.githubusercontent.com/assets/66382/25994894/8451c40a-3718-11e7-972b-ae47e39fa353.png)

#### Selected row focused
![screen shot 2017-05-12 at 13 34 24](https://cloud.githubusercontent.com/assets/66382/25994909/92b568da-3718-11e7-9fc8-5b5ec800e905.png)

Here’s a working CSS snippet for the focus styles (color and border-radius values should be replaced with variables and/or computed values):

```css
.v-tree8-rowmode-cell-focused::after {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  box-sizing: border-box;
  width: 100%;
  height: 100%;
  border: 2px solid transparent;
  box-shadow: inset 0 0 0 1px #197de1;
  border-radius: 4px;
}

.v-tree8-row-selected .v-tree8-rowmode-cell-focused::after {
  box-shadow: inset 0 0 0 1px #fff;
}
```

## Row height 
The row height should be 28px by default (currently 37px), like in the old tree component. You can copy the computation from the old version. A similar Sass variable should be exposed for the new tree: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_tree.scss#L5

## Item icons

If an item has an icon, an extra white space character is added to the item caption. This should be done using CSS margins instead, by wrapping the caption in a new `span` element (which allows more fine-grained control for a theme developer to align the caption and the icon): https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/connectors/tree/TreeRendererConnector.java#L54

The resulting HTML should be like this:

```html
<div class="gwt-HTML v-tree8-cell-content">
  <span class="v-icon Vaadin-Icons"></span>
  <span class="v-captiontext>Desktops</span>
</div>
```

After this change, the white space is automatically provided by the Valo theme: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/shared/_global.scss#L304-L305

## Other issues

- The `$v-tree8-border-radius` for the new tree should be computed instead of hardcoded to `3px`: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss#L3

- `$v-grid-cell-padding` used but not available – this line should be removed: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss#L39
